//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lectionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lectionary.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap border_vert {
            get {
                object obj = ResourceManager.GetObject("border_vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///	  &quot;Day&quot;: &quot;2021-11-17T00:00:00&quot;,
        ///	  &quot;FeastsAndSaints&quot;: &quot;    St. Gregory, Wonderworker of Neo-C\u00E6sarea (ca. 266-270). Ven. Nikon, Abbot of R\u00E1donezh, disciple of Ven. Sergius (1426). Ven. Lazarus the Iconographer, of Constantinople (ca. 857). Martyr Gobron (Michael) and 133 soldiers, of Georgia (914). Ven. Genadius of Vatopedi (Mt. Athos).  &quot;,
        ///	  &quot;Readings&quot;: [
        ///		{
        ///		  &quot;Book&quot;: &quot;Colossians&quot;,
        ///		  &quot;StartChapter&quot;: 3,
        ///		  &quot;EndChapter&quot;: 4,
        ///		  &quot;StartVerse&quot;: 17,
        ///		  &quot;EndVerse&quot;: 1
        ///		},
        ///		{
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lectionary {
            get {
                return ResourceManager.GetString("lectionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;NKJV&quot;, 
        ///  &quot;books&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Genesis&quot;, 
        ///      &quot;chapters&quot;: [
        ///        {
        ///          &quot;verses&quot;: [
        ///            {
        ///              &quot;text&quot;: &quot;In the beginning God created the heavens and the earth.&quot;, 
        ///              &quot;num&quot;: 1
        ///            }, 
        ///            {
        ///              &quot;text&quot;: &quot;The earth was without form, and void; and darkness was on the face of the deep. And the Spirit of God was hovering over the face of the waters.&quot;, 
        ///              &quot;num&quot;: 2
        ///            }, 
        ///            {
        ///              &quot;text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NKJV {
            get {
                return ResourceManager.GetString("NKJV", resourceCulture);
            }
        }
    }
}
